TieuChuanWebVer4/TieuChuanWebVer4/Controllers/NhapThongTinChiTietController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using TieuChuanWebVer4.Models;
namespace TieuChuanWebVer4.Controllers
{
    public class NhapThongTinChiTietController : Controller
    {
        private static Guid _iGuid;
        // GET: NhapThongTinChiTiet
        QL_TieuChuan2Entities db = new QL_TieuChuan2Entities();

        public ActionResult Index()
        {
            if (Session["TaiKhoan"] != null)
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        [ValidateInput(false)]
        public ActionResult NhapThongTinChiTietPartial()
        {
                var model = db.hs_noidung;
                return PartialView("_NhapThongTinChiTietPartial", model.OrderByDescending(n => n.ngaytao).ToList());
        }

        //[HttpPost, ValidateInput(false)]
        //public ActionResult NhapThongTinChiTietPartialAddNew(TieuChuanWebVer4.Models.hs_noidung item)
        //{
        //    var model = db1.hs_noidung;
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            model.Add(item);
        //            db1.SaveChanges();
        //        }
        //        catch (Exception e)
        //        {
        //            ViewData["EditError"] = e.Message;
        //        }
        //    }
        //    else
        //        ViewData["EditError"] = "Please, correct all errors.";
        //    return PartialView("_NhapThongTinChiTietPartial", model.ToList());
        //}
        //[HttpPost, ValidateInput(false)]
        //public ActionResult NhapThongTinChiTietPartialUpdate(TieuChuanWebVer4.Models.hs_noidung item)
        //{
        //    var model = db1.hs_noidung;
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            var modelItem = model.FirstOrDefault(it => it.id == item.id);
        //            if (modelItem != null)
        //            {
        //                this.UpdateModel(modelItem);
        //                db1.SaveChanges();
        //            }
        //        }
        //        catch (Exception e)
        //        {
        //            ViewData["EditError"] = e.Message;
        //        }
        //    }
        //    else
        //        ViewData["EditError"] = "Please, correct all errors.";
        //    return PartialView("_NhapThongTinChiTietPartial", model.ToList());
        //}
        //[HttpPost, ValidateInput(false)]
        //public ActionResult NhapThongTinChiTietPartialDelete(System.Guid id)
        //{
        //    var model = db1.hs_noidung;
        //    if (id != null)
        //    {
        //        try
        //        {
        //            var item = model.FirstOrDefault(it => it.id == id);
        //            if (item != null)
        //                model.Remove(item);
        //            db1.SaveChanges();
        //        }
        //        catch (Exception e)
        //        {
        //            ViewData["EditError"] = e.Message;
        //        }
        //    }
        //    return PartialView("_NhapThongTinChiTietPartial", model.ToList());
        //}
        //View Thêm mới
        public ActionResult ThemMoi()
        {
            if (Session["TaiKhoan"] != null)
            {
                // var da = db.dm_tieuchuan.SingleOrDefault(n => n.id == id);
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        //View Chỉnh sửa
        public ActionResult ChinhSua(System.Guid? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                var da = db.hs_noidung.SingleOrDefault(n => n.id == id);
                return View(da);
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        //View Chỉnh sửa
        public ActionResult Xoa(System.Guid id)
        {
            if (Session["TaiKhoan"] != null)
            {
                var model = db.hs_noidung;
                if (id != null)
                {
                    try
                    {
                        var item = model.FirstOrDefault(it => it.id == id);
                        if (item != null)
                            model.Remove(item);
                        db.SaveChanges();
                    }
                    catch (Exception e)
                    {
                        ViewData["EditError"] = e.Message;
                    }
                }
                return RedirectToAction("Index", "DanhMucTieuChuan");
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        //-------------------------------------- Hiện lên nội dung trong Word
        public ActionResult SaveNewDocument(FormCollection f)
        {
            if (Session["TaiKhoan"] != null)
            {
                Guid id = _iGuid;
                string txtMaTC = f["txtNew_ma_tieuchi"].ToString();
                string txtTenTC = f["txtNew_ten_tieuchi"].ToString();
                var doc = DevExpress.Web.Office.DocumentManager.FindDocument("document" + id);
                string richEditString = Encoding.UTF8.GetString(doc.SaveCopy());
                var model = db.hs_noidung;
                hs_noidung item = new hs_noidung();
                if (ModelState.IsValid)
                {
                    try
                    {
                        item.id = id;
                        item.ma_tieuchi = txtMaTC;
                        item.ten_tieuchi = txtTenTC;
                        item.nguoitao = Session["TenNguoiDung"].ToString();
                        item.ngaytao = DateTime.Now;
                        item.noidung = richEditString;
                        db.hs_noidung.Add(item);
                        db.SaveChanges();
                        //db.sp_ThemMoiND(id, txtMaTC, txtTenTC, Session["TenNguoiDung"].ToString(), DateTime.Now, richEditString);
                        //Thread.Sleep(10000);
                    }
                    catch (Exception e)
                    {
                        ViewData["EditError"] = e.Message;
                    }
                }
                else
                    ViewData["EditError"] = "Please, correct all errors.";
                return View("Index");
                //return Content("<script type='text/javascript'>setInterval(function(){window.close();alert('Lưu thành công !!');window.opener.location.reload(true);},2000);</script>");
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        public ActionResult SaveEditDocument(Guid id, FormCollection f)
        {
            if (Session["TaiKhoan"] != null)
            {
                string txtMaTC = f["txt_ma_tieuchi"].ToString();
                string txtTenTC = f["txt_ten_tieuchi"].ToString();
                var doc = DevExpress.Web.Office.DocumentManager.FindDocument("document" + id);
                string richEditString = Encoding.UTF8.GetString(doc.SaveCopy());
                //string richEditString = Encoding.UTF8.GetString(RichEditExtension.SaveCopy("NoiDung", DocumentFormat.Html));
                var model = db.hs_noidung;
                if (ModelState.IsValid)
                {
                    try
                    {
                        var modelItem = model.FirstOrDefault(it => it.id == id);
                        if (modelItem != null)
                        {
                            //db.sp_CapNhatND(id, txtMaTC, txtTenTC, Session["TenNguoiDung"].ToString(), DateTime.Now, richEditString);
                            // Thread.Sleep(10000);
                            modelItem.id = id;
                            modelItem.ma_tieuchi = txtMaTC;
                            modelItem.ten_tieuchi = txtTenTC;
                            modelItem.nguoisua = Session["TenNguoiDung"].ToString();
                            modelItem.ngaysua = DateTime.Now;
                            modelItem.noidung = richEditString;
                            db.Entry(modelItem).State = EntityState.Modified;
                            db.SaveChanges();
                            // db.hs_noidung.Add(modelItem);


                        }
                    }
                    catch (Exception e)
                    {
                        ViewData["EditError"] = e.Message;
                    }
                }
                else
                    ViewData["EditError"] = "Please, correct all errors.";
                return View("Index");
                // return Content("<script type='text/javascript'>setInterval(function(){window.close();alert('Lưu thành công !!');window.opener.location.reload(true);},2000);</script>");
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        public ActionResult NoiDungThemMoiPartial()
        {
            if (Session["TaiKhoan"] != null)
            {
                var model = db.hs_noidung;
                //var x = model.SingleOrDefault(n => n.id == new Guid("D4EF2CE0-72DE-49CD-8BC7-158CBB8CEB3F"));
                hs_noidung x = new hs_noidung();
                x.id = Guid.NewGuid();
                _iGuid = x.id;
                x.noidung = "";
                x.noidungbyte = Encoding.UTF8.GetBytes(x.noidung);
                return PartialView("_NoiDungThemMoiPartial", x);
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        public ActionResult NoiDungThemMoi1Partial(System.Guid? id)

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/ChinhSua.cshtml
@model TieuChuanWebVer4.Models.hs_noidung
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutWord.cshtml";
}
<script>
    function SelectionChanged(s, e) {
        e.handled = true;
        var url = "/NhapThongTinChiTiet/Dialog?dinhdanh=" + e.targetUri + "&ma_tieuchi=@(Model.ma_tieuchi)";
        //window.location.href = url;
        window.open(url, "_blank", "toolbar=no, menubar=no,scrollbars=no,resizable=no,location=no,directories=no,status=no,left=900,width=520, height=520,scrollbars=yes")

    }
    $(document).ready(function () {
        $('#btnBoLuu').click(function () {
            var url = '@Url.Action("Index", "NhapThongTinChiTiet")';
            window.location.href = url;
           
        });
    });
</script>
@Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit }
    )
@Html.DevExpress().GetScripts(
        new Script { ExtensionSuite = ExtensionSuite.RichEdit }
    )
@using (Html.BeginForm("SaveEditDocument", "NhapThongTinChiTiet"))
{
    @Html.Hidden("id", Model.id)
    @Html.Action("NoiDungPartial")
    <div style="width:93%;height:25px;margin-left: auto;margin-right:auto; margin-top:1% ;">
        <div style="width:40%;float:left;">
            <div style="width:30%;float:left">
                @Html.DevExpress().Label(settings =>
           {
               //settings.Text = "Mã tiêu chí";
               settings.Text = "Criteria Code";
           }).GetHtml()
            </div>
            <div style="width:70%;float:left;">
                @Html.DevExpress().TextBox(settings =>
{
    settings.Name = "txt_ma_tieuchi";
    settings.Text = Model.ma_tieuchi;
    //settings.ReadOnly = true;
    // settings.ClientVisible = false;
}).GetHtml()
            </div>

        </div>
        <div style="width:40%;float:left;">
            <div style="width:30%;float:left;">
                @Html.DevExpress().Label(settings =>
           {
               //settings.Text = "Tên tiêu chí";
               settings.Text = "Criteria Name";
           }).GetHtml()
            </div>
            <div style="width:70%;float:left;">
                @Html.DevExpress().TextBox(settings =>
{
    settings.Name = "txt_ten_tieuchi";
    settings.Text = Model.ten_tieuchi;
    //settings.ReadOnly = true;
    // settings.ClientVisible = false;
}).GetHtml()
            </div>
        </div>
        <div style="width:20%;float:left;">
            @Html.DevExpress().Button(settings =>
   {
       settings.Name = "btnLuu";
       settings.Text = "Save";
       settings.UseSubmitBehavior = true;
       // settings.ClientSideEvents.Click = "fncBtnLuu1Click";
       settings.Images.Image.Url = Url.Content("~/Content/Images/TieuChuan/save.png");
       settings.ImagePosition = ImagePosition.Left;
   }).GetHtml()
            @Html.DevExpress().Button(settings =>
       {
           settings.Name = "btnBoLuu";
           settings.Text = "Cancel";
           // settings.ClientSideEvents.Click = "fncBtnBoLuuClick";
           //settings.UseSubmitBehavior = true;
           settings.Images.Image.Url = Url.Content("~/Content/Images/TieuChuan/notsave.png");
           settings.ImagePosition = ImagePosition.Left;
       }).GetHtml()
        </div>
    </div>
}

<style>
    #frmTieuChuan {
        margin-top: 8px;
    }
</style>

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/DanhSachTaiLieuPartial.cshtml
@model IEnumerable <TieuChuanWebVer4.Models.sp_DanhSachTaiLieu_Result>
    
    @foreach(var item in Model)
    {
       <p>--------@item.tentaptin</p>
    }

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/Dialog.cshtml
@model IEnumerable<TieuChuanWebVer4.Models.sp_DanhSachTaiLieu_Result>
@{
    ViewBag.Title = "Document";
    Layout = "~/Views/Shared/_LayoutWord.cshtml";
}
<style>
    body {
        background-color: lightcyan;
    }
    table{border-collapse:collapse;
          width:500px;
background-color: white;
    }
    tr,td{
        border:1px solid #808080;
    }
    td{
        padding:5px;
           }
</style>
<center>
    <table>
       <tr><td style="font-weight:bold;text-align:center" colspan="2">DOCUMENTS FOR <b style="color:red">@(ViewBag.DinhDanh)</b></td></tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.tentaptin</td>
                <td><a href="https://drive.google.com/open?id=@item.driveid" target="_blank">View</a></td>
            </tr>
        }

    </table>
</center>

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/Index.cshtml
@model IEnumerable<TieuChuanWebVer4.Models.hs_noidung>

@{
    //ViewBag.Title = "Nhập thông tin chi tiết";
    ViewBag.Title = "Input Detail Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script type="text/javascript">
    ribbon.SetActiveTabIndex(1);
    //document.getElementById("ribbon_State").SetActiveTabIndex(1);
    function OnGridFocusedRowChanged(s, e) {
        s.GetRowValues(s.GetFocusedRowIndex(), 'id;ma_tieuchi;ten_tieuchi;noidung', OnGetRowValues);
    }
    function OnGetRowValues(values) {
        txtHiddenId.SetText(values[0]);
        txt_ma_tieuchi.SetText(values[1]);
        txt_ten_tieuchi.SetText(values[2]);
        txt_noidung.SetText(values[3]);
    }
    function fncBtnThemClick() {
        //var x = document.getElementById("txtHiddenId_I").value;
        var url = '@Url.Action("ThemMoi", "NhapThongTinChiTiet")';
        window.location.href = url;
       // window.open(url, "_blank", "toolbar=yes,top=10,left=150,right=150,width=970,height=670");
        //'Url.Action("ChinhSua","DanhMucTieuChuan", { new id= x } )';
        // alert(x);
    }
    function fncBtnSuaClick() {
        var x = document.getElementById("txtHiddenId_I").value;
        var url = '@Url.Action("ChinhSua", "NhapThongTinChiTiet")' + '?id=' + x;
        window.location.href = url;
        //window.open(url, "_blank", "toolbar=yes,top=10,left=150,right=150,width=970,height=670");
        //'Url.Action("ChinhSua","DanhMucTieuChuan", { new id= x } )';
        // alert(x);
    }
    function fncBtnXoaClick() {
        var x = document.getElementById("txtHiddenId_I").value;
        var result = confirm("Are you sure you want to delete?");
        if (result) {
            var url = '@Url.Action("Xoa", "NhapThongTinChiTiet")' + '?id=' + x;
            window.location.href = url;
            alert("Deleted Successfully!!");
        }
        else {
            return false;
        }
    }
</script>
<style>
    #txtHiddenId {
        display: none;
    }

    .cs {
        padding-left: 20px;
        padding-right: 20px;
        padding-bottom: 20px;
        width: 700px;
        border-radius: 20px;
        border: 2px solid blue;
        margin: 0px auto;
        margin-top: 4%;
        margin-bottom: 2%;
    }

    table#NhapThongTinChiTiet {
        width: 30%;
        margin: auto;
    }

    div#khung {
        margin-top: 5%;
    }
</style>

@Html.DevExpress().TextBox(settings =>
    {
        settings.Name = "txtHiddenId";
        settings.ReadOnly = true;
        // settings.ClientVisible = false;
    }).GetHtml()
<div id="khung">
    @Html.Action("NhapThongTinChiTietPartial")
    <div style="width:100%;text-align:center;margin-top:2%">
        @*--------------------------------------Button Thêm*@
        @Html.DevExpress().Button(settings =>
{
    settings.Name = "btnThem";
    settings.Text = "Add";
    settings.ClientSideEvents.Click = "fncBtnThemClick";
}).GetHtml()
        @*--------------------------------------Button Sửa*@
        @Html.DevExpress().Button(settings =>
{
    settings.Name = "btnSua";
    settings.Text = "Edit";
    settings.ClientSideEvents.Click = "fncBtnSuaClick";
}).GetHtml()
        @*--------------------------------------Button Xóa*@
        @Html.DevExpress().Button(settings =>
{
    settings.Name = "btnXoa";
    settings.Text = "Delete";
    settings.ClientSideEvents.Click = "fncBtnXoaClick";
}).GetHtml()
    </div>
</div>
<!--End Modal Sửa-->

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/ThemMoi.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutWord.cshtml";
}
@Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit }
    )
@Html.DevExpress().GetScripts(
        new Script { ExtensionSuite = ExtensionSuite.RichEdit }
    )
@using (Html.BeginForm("SaveNewDocument", "NhapThongTinChiTiet"))
{
        @Html.Action("NoiDungThemMoiPartial")
    <div style="width:93%;height:25px;margin-left: auto;margin-right:auto; margin-top:1% ;">
        <div style="width:40%;float:left;">
            <div style="width:30%;float:left">
                @Html.DevExpress().Label(settings =>
           {
               //settings.Text = "Mã tiêu chí";
               settings.Text = "Criteria Code";
           }).GetHtml()
            </div>
            <div style="width:70%;float:left;">
                @Html.DevExpress().TextBox(settings =>
       {
           settings.Name = "txtNew_ma_tieuchi";
           settings.Width = Unit.Percentage(100);
       }).GetHtml()
            </div>
        </div>
        <div style="width:40%;float:left;">
            <div style="width:30%;float:left;">
                @Html.DevExpress().Label(settings =>
           {
               // settings.Text = "Tên tiêu chí";
               settings.Text = "Criteria Name";
           }).GetHtml()
            </div>
            <div style="width:70%;float:left;">
                @Html.DevExpress().TextBox(settings =>
       {
           settings.Name = "txtNew_ten_tieuchi";
           settings.Width = Unit.Percentage(100);
       }).GetHtml()
            </div>
        </div>
        <div style="width:20%;float:left;">
            @Html.DevExpress().Button(settings =>
       {
           settings.Name = "btnLuu";
           settings.Text = "Save";
           settings.UseSubmitBehavior = true;
           //settings.ClientSideEvents.Click = "fncBtnLuu1Click";
           settings.Images.Image.Url = Url.Content("~/Content/Images/TieuChuan/save.png");
           settings.ImagePosition = ImagePosition.Left;
       }).GetHtml()
            @Html.DevExpress().Button(settings =>
       {
           settings.Name = "btnBoLuu";
           settings.Text = "Cancel";
           // settings.ClientSideEvents.Click = "fncBtnBoLuuClick";
           //settings.UseSubmitBehavior = true;
           settings.Images.Image.Url = Url.Content("~/Content/Images/TieuChuan/notsave.png");
           settings.ImagePosition = ImagePosition.Left;
       }).GetHtml()
        </div>
    </div>

}
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnBoLuu').click(function () {
            var url = '@Url.Action("Index", "NhapThongTinChiTiet")';
            window.location.href = url;
        });
    });
</script>

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/_NhapThongTinChiTietPartial.cshtml
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "NhapThongTinChiTiet";
        settings.CallbackRouteValues = new { Controller = "NhapThongTinChiTiet", Action = "NhapThongTinChiTietPartial" };

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "NhapThongTinChiTiet", Action = "NhapThongTinChiTietPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "NhapThongTinChiTiet", Action = "NhapThongTinChiTietPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "NhapThongTinChiTiet", Action = "NhapThongTinChiTietPartialDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.CommandColumn.Visible = true;
        //settings.CommandColumn.ShowNewButton = true;
        //settings.CommandColumn.ShowDeleteButton = true;
        //settings.CommandColumn.ShowEditButton = true;

        settings.KeyFieldName = "id";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = false;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.SettingsBehavior.AllowFocusedRow = true;

        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.Off;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;

        //settings.Columns.Add("ma_tieuchi");
        settings.Columns.Add(column =>
        {
            column.FieldName = "ma_tieuchi";
            //column.Caption = "Mã tiêu chí";
            column.Caption = "Criteria Code";
        });
        // settings.Columns.Add("ten_tieuchi");
        settings.Columns.Add(column =>
        {
            column.FieldName = "ten_tieuchi";
            //column.Caption = "Tên tiêu chí";
            column.Caption = "Criteria Name";
        });
        //settings.Columns.Add("noidung");

        settings.ClientSideEvents.FocusedRowChanged = "OnGridFocusedRowChanged";

        settings.SettingsPager.PageSize = 12;
        settings.SettingsPager.FirstPageButton.Visible = true;
        settings.SettingsPager.FirstPageButton.Text = "First page";
        settings.SettingsPager.LastPageButton.Visible = true;

        settings.SettingsPager.LastPageButton.Text = "Last page";
        settings.SettingsPager.Summary.Text = " Page {0}/{1} (Criteria Total: {2})";
        settings.PreRender = (s, e) =>
        {
            var sender = s as MVCxGridView;
            // Set the zero-based index of the initially displayed page
            sender.PageIndex = 0;
        };

    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/_NoiDungPartial.cshtml
@model TieuChuanWebVer4.Models.hs_noidung
@Html.DevExpress().RichEdit(settings =>
{
    settings.Name = "NoiDung";
    settings.CallbackRouteValues = new { Controller = "NhapThongTinChiTiet", Action = "NoiDungPartial", id = Model.id };
    settings.Width = Unit.Percentage(100);
    settings.Height = 610;
    settings.ReadOnly = false;
    settings.RibbonMode = RichEditRibbonMode.OneLineRibbon;
    settings.Settings.HorizontalRuler.Visibility = DevExpress.XtraRichEdit.RichEditRulerVisibility.Hidden;
    // settings.ViewMergedData = true;
    //settings.= "function(s, e) { DXEventMonitor.Trace(s, e, 'GotFocus') }";
    settings.Init = (s, e) =>
    {
        var rich = s as MVCxRichEdit;
        rich.CreateDefaultRibbonTabs(true);
        //rich.RibbonTabs[0].Visible = false;
        //rich.RibbonTabs[2].Visible = false;
        //rich.RibbonTabs[3].Visible = false;
        //rich.RibbonTabs[4].Visible = false;
        //rich.RibbonTabs[5].Visible = false;
    };
    settings.EnableClientSideAPI = true;
    settings.ClientSideEvents.HyperlinkClick="SelectionChanged";
    //string.Format("function (s,e) {{ OnMoreInfoClick1({0}); }}", Model.id);
    settings.Saving = (s, e) =>
    {
        byte[] docBytes = RichEditExtension.SaveCopy("NoiDung", DevExpress.XtraRichEdit.DocumentFormat.Html);
        //DXWebApplication1.Models.DataHelper.SaveDocument(docBytes);
        e.Handled = true;
    };
}).Open("document" + Model.id, DevExpress.XtraRichEdit.DocumentFormat.Html, () => { return Model.noidungbyte; }).GetHtml()
@*@Html.Hidden("id", Model.id)*@

TieuChuanWebVer4/TieuChuanWebVer4/Views/NhapThongTinChiTiet/_NoiDungThemMoiPartial.cshtml
@model TieuChuanWebVer4.Models.hs_noidung

@Html.DevExpress().RichEdit(settings =>
{
    settings.Name = "NoiDungThemMoi";
    settings.CallbackRouteValues = new { Controller = "NhapThongTinChiTiet", Action = "NoiDungThemMoi1Partial", id = Model.id };
    settings.Width = Unit.Percentage(100);
    settings.Height = 610;
    settings.ReadOnly = false;
    settings.RibbonMode = RichEditRibbonMode.OneLineRibbon;
    settings.Settings.HorizontalRuler.Visibility = DevExpress.XtraRichEdit.RichEditRulerVisibility.Hidden;
    settings.Init = (s, e) =>
    {
        var rich = s as MVCxRichEdit;
        rich.CreateDefaultRibbonTabs(true);
        //rich.RibbonTabs[0].Visible = false;
        //rich.RibbonTabs[2].Visible = false;
        //rich.RibbonTabs[3].Visible = false;
        //rich.RibbonTabs[4].Visible = false;
        //rich.RibbonTabs[5].Visible = false;
    };
    settings.Saving = (s, e) =>
    {
        byte[] docBytes = RichEditExtension.SaveCopy("NoiDung", DevExpress.XtraRichEdit.DocumentFormat.Html);
        //DXWebApplication1.Models.DataHelper.SaveDocument(docBytes);
        e.Handled = true;
    };
}).Open("document" + Model.id, DevExpress.XtraRichEdit.DocumentFormat.Html, () => { return Model.noidungbyte; }).GetHtml()