TieuChuanWebVer4/TieuChuanWebVer4/Controllers/XemChiTietTieuChuanController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TieuChuanWebVer4.Models;
namespace TieuChuanWebVer4.Controllers
{
    public class XemChiTietTieuChuanController : Controller
    {
        // GET: XemChiTietTieuChuan
        QL_TieuChuan2Entities db = new QL_TieuChuan2Entities();
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] != null)
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        [ValidateInput(false)]
        public ActionResult TreeListPartial()
        {
            if (Session["TaiKhoan"] != null)
            {
                var model = (from g in db.sp_DuLieuGoc()
                             join ct in db.sp_DuLieuChiTiet()
                             on g.ma_nhom equals ct.ma_tieuchi
                             select new
                             {
                                 nhom = g.nhom,
                                 ma_nhom = g.ma_nhom,
                                 ten_nhom = g.ten_nhom,
                                 ma_nhom_cha = g.ma_nhom_cha,
                                 ma_tieuchi = ct.ma_tieuchi,
                                 noidung = ct.noidung,
                                 noidungbyte = Encoding.UTF8.GetBytes(ct.noidung)
                             }
                             ).ToList();
                return PartialView("_TreeListPartial", model);
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        public ActionResult RichEditPartial(string ma_tieuchi)
        {
            if (Session["TaiKhoan"] != null)
            {
                var model = db.sp_DuLieuChiTiet();
                //var x = model.SingleOrDefault(n => n.id == new Guid("D4EF2CE0-72DE-49CD-8BC7-158CBB8CEB3F"));
                var x = model.SingleOrDefault(n => n.ma_tieuchi == ma_tieuchi);
                // byte[] docBytes = RichEditExtension.SaveCopy("RichEditName", DevExpress.XtraRichEdit.DocumentFormat.Rtf);
                byte[] nd = Encoding.UTF8.GetBytes(x.noidung);
                x.noidungbyte = nd;
                //var y = model.SingleOrDefault(n => n.id == (System.Guid)id);
                return PartialView("_RichEditPartial", x);
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
    }
}

TieuChuanWebVer4/TieuChuanWebVer4/Views/XemChiTietTieuChuan/Index.cshtml

@{
    //ViewBag.Title = "Xem chi tiết tiêu chuẩn";
    ViewBag.Title = "View Detail Standard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    ribbon.SetActiveTabIndex(1);
    //function OnNodeClick(s, e) {
    //    alert(e.nodeKey);
    //    //window.location.href = "Url.Action("RichEditPartial1", "Home")" + "?ma_tieuchi=" + e.nodeKey;
    //}
    function OnNodeClick(s, e) {
        s.GetNodeValues(e.nodeKey, "ma_nhom;ten_nhom;noidung", OnCallback);
    }
    function OnCallback(values) {
        //RichEdit.commands.insertText.execute(values[1]);

        @*var url = "@Url.Action("RichEdit1", "Home")" + "?ma_tieuchi=" + values[0];
        window.open(url, "_blank", "left=700,width=900,height=900");*@

        //$('#RichEdit').load('/Home/RichEditPartial?ma_tieuchi='+values[1]);
        //$('#mydiv').replaceAll("Url.Action("RichEdit1", "Home")" + "?ma_tieuchi=" + values[0]);

        var url = '@Url.Action("RichEditPartial", "XemChiTietTieuChuan")';
        url += '/?ma_tieuchi=' + values[0];
        $("#mydiv").load(url);
    }
</script>

@Html.DevExpress().Panel(settings =>
{
    settings.Name = "Left1Panel";
    settings.FixedPosition = PanelFixedPosition.WindowLeft;
    //settings.FixedPosition = PanelFixedPosition.WindowLeft;
    //settings.SettingsCollapsing.ExpandEffect = PanelExpandEffect.PopupToLeft;
    settings.Collapsible = false;
    //settings.SettingsAdaptivity.CollapseAtWindowInnerWidth = 450;
    settings.Width = 330;
    settings.ScrollBars = ScrollBars.Auto;
    settings.SetContent(() =>
    {
        //ViewContext.Writer.Write(@"<input id='myButton' type='button' value='Button' />");
        Html.RenderPartial("Left1PanelPartial");
    });
}).GetHtml()
@Html.DevExpress().Panel(settings =>
{
    settings.Name = "Right1Panel";
    // settings.FixedPosition = PanelFixedPosition.None;
    //settings.FixedPosition = PanelFixedPosition.None;
    settings.Height= Unit.Percentage(100);
    //settings.SettingsCollapsing.ExpandEffect = PanelExpandEffect.;
    settings.SettingsCollapsing.ExpandEffect = PanelExpandEffect.Auto;
    settings.ScrollBars = ScrollBars.Auto;
    settings.Collapsible = false;
    //settings.SettingsAdaptivity.CollapseAtWindowInnerWidth =Control.Unit.Percentage(100);
    settings.SetContent(() =>
    {
        //ViewContext.Writer.Write(@"<div style='width:800px;height:800px'>ry</div>");
        Html.RenderPartial("Right1PanelPartial");
    });
}).GetHtml()


TieuChuanWebVer4/TieuChuanWebVer4/Views/XemChiTietTieuChuan/Left1PanelPartial.cshtml


@Html.Action("TreeListPartial")

TieuChuanWebVer4/TieuChuanWebVer4/Views/XemChiTietTieuChuan/Right1PanelPartial.cshtml

<div id="mydiv">
    @Html.Action("RichEditPartial", "XemChiTietTieuChuan", new { ma_tieuchi = "TC10.3" })
</div>

TieuChuanWebVer4/TieuChuanWebVer4/Views/XemChiTietTieuChuan/_RichEditPartial.cshtml
@model TieuChuanWebVer4.Models.sp_DuLieuChiTiet_Result
@Html.DevExpress().RichEdit(settings =>
{
    settings.Name = "RichEdit";
    settings.CallbackRouteValues = new { Controller = "XemChiTietTieuChuan", Action = "RichEditPartial", ma_tieuchi = Model.ma_tieuchi };
    settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
    settings.RibbonMode = RichEditRibbonMode.OneLineRibbon;
    settings.Height = 640;
    settings.ReadOnly = false;
    // settings.RibbonMode = RichEditRibbonMode.Ribbon;
    settings.EnableClientSideAPI = true;
    settings.ClientSideEvents.HyperlinkClick = "HyperlinkClick";
    //settings.WorkDirectory = Server.MapPath("~/Documents/");
    //settings.Settings.Behavior.SaveAllowed = false;
    //settings.Settings.Behavior.CreateNewAllowed = false;
    //settings.Settings.Behavior.OpenAllowed = false;
    //settings.Settings.Behavior.SaveAsAllowed = false;
    settings.Init = (s, e) =>
    {
        var rich = s as MVCxRichEdit;
        rich.CreateDefaultRibbonTabs(true);
        // rich.RibbonTabs[0].Visible = false;
        rich.RibbonTabs[1].Visible = false;
        rich.RibbonTabs[2].Visible = false;
        rich.RibbonTabs[3].Visible = false;
        rich.RibbonTabs[4].Visible = false;
        rich.RibbonTabs[5].Visible = false;
        rich.Settings.Behavior.Save = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
        rich.Settings.Behavior.SaveAs = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
        rich.Settings.Behavior.Open = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
        rich.Settings.Behavior.CreateNew = DevExpress.XtraRichEdit.DocumentCapability.Hidden;
    };
    settings.Saving = (source, args) =>
    {
        //  var bytes = RichEditExtension.SaveCopy("RichEdit", DevExpress.XtraRichEdit.DocumentFormat.Rtf);
        var bytes = RichEditExtension.SaveCopy("RichEdit", DevExpress.XtraRichEdit.DocumentFormat.Rtf);
        args.Handled = true;
    };
}).Open("document" + Model.ma_tieuchi, DevExpress.XtraRichEdit.DocumentFormat.Html, () => { return Model.noidungbyte; }).GetHtml()
<script>
    function HyperlinkClick(s, e) {
        e.handled = true;
        var url = "/NhapThongTinChiTiet/Dialog?dinhdanh=" + e.targetUri + "&ma_tieuchi=@(Model.ma_tieuchi)";
        //window.location.href = url;
        window.open(url, "_blank", "toolbar=no, menubar=no,scrollbars=no,resizable=no,location=no,directories=no,status=no,left=900,width=520, height=520,scrollbars=yes")
    }
</script>

TieuChuanWebVer4/TieuChuanWebVer4/Views/XemChiTietTieuChuan/_TreeListPartial.cshtml
@{
    var treeList = Html.DevExpress().TreeList(settings =>
    {
        settings.Name = "TreeList";
        settings.CallbackRouteValues = new { Controller = "XemChiTietTieuChuan", Action = "TreeListPartial" };


        settings.KeyFieldName = "ma_nhom";
        settings.ParentFieldName = "ma_nhom_cha";
        //settings.Columns.Add(
        //        column => {
        //            column.FieldName = "nhom";
        //        }
        //    );
        settings.Columns.Add(
    column =>
    {
        column.FieldName = "ma_nhom";
        column.Visible = false;
    }
);
        settings.Columns.Add(
    column =>
    {
        column.FieldName = "ten_nhom";
        // column.Caption = "Tên nhóm";
        column.Caption = "Group Name";
    }
);
        settings.Columns.Add(
   column =>
   {
       column.FieldName = "noidung";
       //column.Caption = "Nội dung"; 
       column.Caption = "Content";
       column.Visible = false;
   }
);
        //        settings.Columns.Add(
        //    column => {
        //        column.FieldName = "ma_nhom_cha";
        //    }
        //);

        settings.SettingsPager.Visible = true;
        settings.SettingsCookies.StoreExpandedNodes = true;
        settings.Settings.ShowTreeLines = true;
        settings.Settings.GridLines = System.Web.UI.WebControls.GridLines.Horizontal;
        //  settings.SettingsBehavior.ExpandCollapseAction = DevExpress.Web.ASPxTreeList.TreeListExpandCollapseAction.Button;
        settings.SettingsBehavior.AllowFocusedNode = true;
        //settings.Styles.FocusedNode.BackColor = System.Drawing.Color.FromArgb(0, 170, 198);
        //settings.Styles.SelectionCell.BackColor = System.Drawing.Color.FromArgb(0, 170, 198);
        //settings.Styles.SelectedNode.BackColor = System.Drawing.Color.FromArgb(0, 170, 198);
        //settings.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
        settings.Width = 300;
        //settings.Height = 1000;
        settings.Settings.SuppressOuterGridLines = true;
        settings.ClientSideEvents.NodeClick = "OnNodeClick";
        settings.PreRender = (sender, e) =>
        {
            //if (Session["TreeListState"] == null)
            ((MVCxTreeList)sender).ExpandToLevel(2);
        };
    });
}
@treeList.Bind(Model).GetHtml()